name: loan
version: 3.0.1-beta.0
source: contracts
packages:
  - path: contracts/MapleLoan.sol
    contractName: MapleLoan
  - path: contracts/MapleLoanFactory.sol
    contractName: MapleLoanFactory
  - path: contracts/MapleLoanInitializer.sol
    contractName: MapleLoanInitializer
  - path: contracts/Refinancer.sol
    contractName: Refinancer
customDescription: Maple Loan Artifacts and ABIs
