name: fixed-term-loan
version: 5.0.2
source: contracts
packages:
  - path: contracts/MapleLoan.sol
    contractName: MapleLoan
  - path: contracts/MapleLoanFactory.sol
    contractName: MapleLoanFactory
  - path: contracts/MapleLoanFeeManager.sol
    contractName: MapleLoanFeeManager
  - path: contracts/MapleLoanInitializer.sol
    contractName: MapleLoanInitializer
  - path: contracts/MapleLoanV5Migrator.sol
    contractName: MapleLoanV5Migrator
  - path: contracts/Refinancer.sol
    contractName: Refinancer
customDescription: Maple Fixed Term Loan Artifacts and ABIs
